version: '3'

services:
  stripe-cli:
    image: stripe/stripe-cli:latest
    container_name: stripe-cli
    volumes:
      - ./scripts:/scripts 
    entrypoint: ["/bin/sh", "/scripts/entrypoint.sh"] 
    networks:
      - microservice-network

networks:
  microservice-network:
    name: microservice-network
    driver: bridge
    external: true