version: '3.8'

services:
  ngrok:
    build: .
    ports:
      - "4040:4040"  # Expose ngrok's web interface for debugging
    networks:
      - microservice-network

networks:
  microservice-network:
    name: microservice-network
    driver: bridge
    external: true
