services:
    consul:
        image: consul:1.15.4
        container_name: consul_server
        hostname: consul
        networks:
            - microservice-network
        ports:
            - "8500:8500"
        command: agent -server -bootstrap -ui -client=0.0.0.0

networks:
    microservice-network:
        name: microservice-network
        driver: bridge
        external: true
