const initialData = {
    admin: {
      email: 'admin@charitan.com',
      password: 'adminpassword',
    },
    charities: [
      { type: 'Person', country: 'Vietnam', companyName: 'Individual VN', category: ['Humanitarian'], region: ['Asia'] , avatar: "logo1.jpg"},
      { type: 'Person', country: 'USA', companyName: 'Individual USA' , category: ['Humanitarian'], region: ['North America'], avatar: "logo2.jpg"},
      { type: 'Company', country: 'South Africa', companyName: 'Company SA', category: ['Food'], region: ['Africa'], avatar: "logo3.jpg"},
      { type: 'Company', country: 'Germany', companyName: 'Company DE' , category: ['Humanitarian', 'Education'], region: ['Europe, Asia'], avatar: "logo4.jpg"},
      { type: 'Non-profit Organization', country: 'Ukraine', companyName: 'Non-profit UA' , category: ['Humanitarian'], region: ['Europe'], avatar: "logo5.jpg" },
      { type: 'Non-profit Organization', country: 'Israel', companyName: 'Non-profit IL' , category: ['Health'], region: ['Africa'], avatar: "logo6.jpg"},
    ],
    categories: ['Food', 'Health', 'Education', 'Environment', 'Religion', 'Humanitarian', 'Housing', 'Other'],
    regions: ['Africa', 'Asia', 'Europe', 'North America', 'South America', 'Australia', 'Antarctica'],
    globalProjects: [
      {
        title: 'Middle East Crisis',
        description: 'Aid for Middle East Crisis',
        duration: 6,
        goalAmount: 1000000,
        charityCompanyName: 'Non-profit IL',
        category: 'Health',
        region: 'Africa',
        images: ["project1.jpg", "project2.jpg", "project3.jpg"],
      },
      {
        title: 'Ukraine - Russia War',
        description: 'Support for Ukraine in the Russia-Ukraine conflict',
        duration: 12,
        goalAmount: 2000000,
        charityCompanyName: 'Non-profit UA',
        category: 'Humanitarian', 
        region: 'Europe', 
        images: ["project4.jpg", "project5.jpg"],
      },
      {
        title: 'Food Program in South Africa',
        description: 'Food aid in Southern Africa',
        duration: 3,
        goalAmount: 500000,
        charityCompanyName: 'Company SA',
        category: 'Food', 
        region: 'Africa', 
        images: ["project6.jpg", "project7.jpg"],
      },
    ],
    
    localProjects: [
      {
        title: 'Yagi Typhoon Support',
        description: 'Support for Yagi Typhoon victims in Vietnam',
        duration: 3,
        goalAmount: 300000,
        charityCompanyName: 'Individual VN',
        category: 'Humanitarian',
        region: 'Asia', 
        country: 'VN',
        images: ["project8.jpg", "project9.jpg"],
      },
      {
        title: 'Milton Hurricane Support',
        description: 'Support for Milton Hurricane victims in the USA',
        duration: 3,
        goalAmount: 300000,
        charityCompanyName: 'Individual USA',
        category: 'Humanitarian', 
        region: 'North America', 
        country: 'US',
        images: ["project10.jpg"],
      },
      {
        title: 'Helping Ukrainian Refugee',
        description: 'Aid for Ukrainian refugees in Germany',
        duration: 3,
        goalAmount: 300000,
        charityCompanyName: 'Company DE',
        category: 'Humanitarian', 
        region: 'Europe',
        country: 'UA',
        images: ["project11.jpg", "project12.jpg"],
      },
      {
        title: "Supporting SOS Children’s Village",
        description: "Support for SOS Children's Village in China",
        duration: 3,
        goalAmount: 300000,
        charityCompanyName: 'Company DE',
        category: 'Education', 
        region: 'Asia', 
        country: 'CN',
        images: ["project13.jpg", "project14.jpg"],
      },
    ],
  };
  
  module.exports = initialData;
    