version: '3.8'

services:
  emailservice:
    build: ./EmailService
    container_name: email_service
    hostname: email_service
    env_file:
      - .env
    networks:
      - microservice-network
    ports:
      - 8001:8001

  projectmanagementservice:
    build: ./ProjectManagementService
    container_name: project_management_service
    hostname: project_management_service
    env_file:
      - .env
    networks:
      - microservice-network
    ports:
      - 8002:8002

  donationservice:
    build: ./DonationService
    container_name: donation_service
    hostname: donation_service
    env_file:
      - .env
    networks:
      - microservice-network
    ports:
      - 8003:8003
    depends_on:
      - projectmanagementservice

  shardedprojectservice:
    build: ./ShardedProjectService
    container_name: sharded_project_service
    hostname: sharded_project_service
    env_file:
      - .env
    networks:
      - microservice-network
    ports:
      - 8004:8004
    depends_on:
      - projectmanagementservice
      
networks:
  microservice-network:
    name: microservice-network
    driver: bridge
    external: true
