version: '3.8'

services:
  emailservice:
    build: ./EmailService
    container_name: email_service
    hostname: email_service
    env_file:
      - .env
    networks:
      - microservice-network
    ports:
      - 3001:3001

  authservice:
    build: ./AuthService
    container_name: auth_service
    hostname: auth_service
    env_file:
      - .env
    networks:
      - microservice-network
    ports:
      - 3000:3000
    depends_on:
      - emailservice

  charitymanagementservice:
    build: ./CharityManagementService
    container_name: charity_management_service
    hostname: charity_management_service
    env_file:
      - .env
    networks:
      - microservice-network
    ports:
      - 3002:3002
    depends_on:
      - authservice
      - emailservice

  projectmanagementservice:
    build: ./ProjectManagementService
    container_name: project_management_service
    hostname: project_management_service
    env_file:
      - .env
    networks:
      - microservice-network
    ports:
      - 3003:3003
    depends_on:
      - charitymanagementservice
      - fileuploadservice

  fileuploadservice:
    build: ./FileUploadService
    container_name: file_upload_service
    hostname: file_upload_service
    env_file:
      - .env
    networks:
      - microservice-network
    ports:
      - 3004:3004
    depends_on:
      - charitymanagementservice

  donationservice:
    build: ./DonationService
    container_name: donation_service
    hostname: donation_service
    env_file:
      - .env
    networks:
      - microservice-network
    ports:
      - 3005:3005
    depends_on:
      - projectmanagementservice

  deleteshardservice:
    build: ./DeleteShardService
    container_name: delete_shard_service
    hostname: delete_shard_service
    env_file:
      - .env
    networks:
      - microservice-network
    ports:
      - 3006:3006
    depends_on:
      - projectmanagementservice

  documentationservice:
    build: ./DocumentationService
    container_name: documentation_service
    hostname: documentation_service
    env_file:
      - .env
    networks:
      - microservice-network
    ports:
      - 3007:3007
    depends_on:
      - emailservice
      - authservice
      - charitymanagementservice
      - projectmanagementservice
      - fileuploadservice
      - donationservice
      - deleteshardservice

  cryptservice:
    build: ./CryptService
    container_name: crypt_service
    hostname: crypt_service
    env_file:
      - .env
    networks:
      - microservice-network
    ports:
      - 3008:3008

networks:
  microservice-network:
    name: microservice-network
    driver: bridge
    external: true
